export const SHOW_PDF_VIEW = 'SHOW_PDF_VIEW'
export const REFRESH_INITIATED = 'REFRESH_INITIATED'
export const INITIATE_REFRESH = 'INITIATE_REFRESH'
export const SHOW_PAYMENT_VIEW = 'SHOW_PAYMENT_VIEW'
